---
# tasks file for K8s_init_master_node

- name: K8s start
  shell: sudo kubeadm init \ --apiserver-advertise-address={{ ansible_host }} \ --pod-network-cidr 10.10.0.0/16
  when: "'master' in group_names"

- name: Copy join command + token
  shell: kubeadm token create --print-join-command
  register: join_command_raw
  when: "'master' in group_names"

- name: Debug join command + token
  debug:
    msg: " {{join_command_raw}} "

- name: Set join command fact
  set_fact:
    join_command: "{{ join_command_raw.stdout }}"
  when: "'master' in group_names"

- name: Create .kube dir in home path
  file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
    mode: '0755'

- name: Copy config files
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ ansible_user }}/.kube/config"
    remote_src: yes

- name: Change ownership
  file:
    path: $HOME/.kube/config
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
  become: yes
  become_user: "{{ansible_user}}"