- name: Install packages
  apt:
    name: "{{package_list}}"
    state: present

- name: Block K8s moduls upgrade
  shell: apt-mark hold kubelet kubeadm kubectl
  become: yes

- name: Enable and start kubelet service
  systemd:
    name: kubelet
    enabled: yes
    state: started
  become: yes

- name: Install kernel modul
  shell: modprobe br_netfilter
  become: yes

- name: Install kernel modul
  shell: modprobe overlay
  become: yes

- name: Enabble IP forwarding
  lineinfile:
    path: /etc/sysctl.conf
    line: 'net.ipv4.ip_forward=1'
    create: yes

- name: Configure sysctl for Kubernetes
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.ipv4.ip_forward = 1
  become: yes


- name: Apply sysctl settings
  command: sysctl --system
  become: yes

- name: Set net.ipv4.ip_forward to 1
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    sysctl_set: yes
    reload: yes
  become: yes

- name: Create dir for containerd configs
  file:
    path: /etc/containerd/
    state: directory
    mode: '0755'
  become: yes

- name: Containerd template moving
  template:
    src: config.toml.j2
    dest: /etc/containerd/config.toml

- name: Restart containerd service
  systemd:
    name: containerd
    state: restarted
  become: yes

